name: Nightly Scrape
on:
  schedule:
    - cron: '0 5 * * *' # Runs at 11:00 PM Central Time daily
  workflow_dispatch: # Allows you to click a button to run it manually
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r web/requirements.txt
      - name: Run Scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scraper/main.py